# Generated by Django 3.1.6 on 2021-03-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('home', 'Home'), ('card', 'Card')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('offres', models.IntegerField(choices=[(30, 'One Monthe'), (60, 'Two Monthes'), (90, 'Three Monthes')])),
                ('image', models.ImageField(upload_to='pubs')),
                ('link_to', models.CharField(blank=True, max_length=2000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PubsTotalStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pub', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PubStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('costumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.costumer')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pub.pub')),
            ],
        ),
    ]
