# Generated by Django 3.1.6 on 2021-03-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210318_1027'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentViewd',
            new_name='ContentViewed',
        ),
        migrations.RenameField(
            model_name='contentviewed',
            old_name='dat_time',
            new_name='date_time',
        ),
    ]
